# Generated by Django 3.2.7 on 2021-10-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(choices=[('Student', 'Student'), ('Veteran', 'Veteran'), ('Expert', 'Expert'), ('Professional', 'Professional')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('joined_on', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(to='mainframe.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.user')),
                ('tags', models.ManyToManyField(to='mainframe.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('commented_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.post')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.user')),
            ],
        ),
    ]
