# Generated by Django 3.2.7 on 2021-10-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0003_rename_post_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_on',
            new_name='comment_of',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainframe.question'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=2),
        ),
    ]
