# Generated by Django 3.2.7 on 2021-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0004_auto_20211009_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
