# Generated by Django 3.2.7 on 2021-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0007_auto_20211009_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_of',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_of',
            new_name='question',
        ),
    ]
