# Generated by Django 3.2.7 on 2021-10-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0010_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerCount',
            field=models.IntegerField(default=0),
        ),
    ]
