# Generated by Django 3.2.7 on 2021-10-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0014_downvotea_downvoteq_upvotea_upvoteq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
