# Generated by Django 3.2.7 on 2021-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0015_remove_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvoteq',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
