# Generated by Django 3.2.7 on 2021-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0016_upvoteq_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvoteq',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
