# Generated by Django 3.2.7 on 2021-10-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0017_downvoteq_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.user')),
            ],
        ),
    ]
