# Generated by Django 3.2.7 on 2021-10-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0018_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvoteq',
            name='done',
        ),
        migrations.RemoveField(
            model_name='upvoteq',
            name='done',
        ),
    ]
