# Generated by Django 3.2.7 on 2021-10-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0019_auto_20211014_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
