# Generated by Django 3.2.7 on 2021-10-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0020_auto_20211014_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownvoteA',
        ),
    ]
