# Generated by Django 3.2.7 on 2021-10-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0022_remove_upvotea_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotea',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainframe.user'),
        ),
    ]
