# Generated by Django 3.2.7 on 2021-10-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0023_upvotea_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.answer')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.user')),
            ],
        ),
    ]
